export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const SEARCH_TV = "SEARCH_TV";
export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_REQUEST_FAIL = "SEARCH_REQUEST_FAIL";
export const SEARCH_REQUEST_SUCCESS = "SEARCH_REQUEST_SUCCESS";

export const GET_MOVIE_INFO = "GET_MOVIE_INFO";
export const GET_TV_INFO = "GET_TV_INFO";
export const GET_REQUEST = "GET_REQUEST";
export const GET_REQUEST_FAIL = "GET_REQUEST_FAIL";
export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS";

export const ADD_NEW_MOVIE = "ADD_NEW_MOVIE";
export const ADD_NEW_TV = "ADD_NEW_TV";
export const ADD_RESET = "ADD_RESET";
export const ADD_REQUEST = "ADD_REQUEST";
export const ADD_REQUEST_FAIL = "ADD_REQUEST_FAIL";
export const ADD_REQUEST_SUCCESS = "ADD_REQUEST_SUCCESS";
export const ADD_TV_REQUEST_SUCCESS = "ADD_TV_REQUEST_SUCCESS";
export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const GET_TV_DETAIL = "GET_TV_DETAIL";
export const GET_DETAIL_REQUEST = "GET_DETAIL_REQUEST";
export const GET_DETAIL_REQUESTT_FAIL = "GET_DETAIL_REQUESTT_FAIL";
export const GET_DETAIL_REQUEST_SUCCESS = "GET_DETAIL_REQUEST_SUCCESS";
