export const GET_NEWEST = "GET_NEWEST"
export const GET_POPULAR = "GET_POPULAR"
export const GET_FAVOR = "GET_FAVOR"
export const GET_EPISODE = "GET_EPISODE"
export const GET_COMMENT = "GET_COMMENT"
export const LOAD_COMMENT = "LOAD_COMMENT"