export const GET_TVSHOW = "GET_TVSHOW";
export const GET_MOVIE = "GET_MOVIE";
export const GET_WATCHLATER = "GET_WATCHLATER";
export const GET_EPISODE = "GET_EPISODE";
export const GET_COMMENT = "GET_COMMENT";
export const LOAD_COMMENT = "LOAD_COMMENT";

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_REQUEST_FAIL = "DELETE_REQUEST";
export const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS";
