export const FORGOT_RESET = "FORGOT_RESET";
export const FORGOT_REQUEST = "FORGOT_REQUEST";
export const FORGOT_SUCCESS = "FORGOT_SUCCESS";
export const FORGOT_FAIL = "FORGOT_FAIL";


export const SENDPASSWORD_SUCCESS = "SENDPASSWORD_SUCCESS";
export const SENDPASSWORD_FAIL = "SENDPASSWORD_FAIL";
export const SENDPASSWORD_REQUEST = "SENDPASSWORD_REQUEST";
export const SENDPASSWORD_RESET = "SENDPASSWORD_RESET";