export const GET_HISTORY_REQUEST = "GET_HISTORY_REQUEST";
export const GET_HISTORY_SUCCESS = "GET_HISTORY_SUCCESS";
export const GET_HISTORY_FAIL = "GET_HISTORY_FAIL";
export const ADD_HISTORY_REQUEST = "ADD_HISTORY_REQUEST";
export const ADD_HISTORY_SUCCESS = "ADD_HISTORY_SUCCESS";
export const ADD_HISTORY_FAIL = "ADD_HISTORY_FAIL";